/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import server.GameServer2;
import common.Config;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import server.GameServer;

/**
 *
 * @author fvarelo
 */
public class Partidas extends javax.swing.JFrame {

    /**
     * Creates new form Partida
     */
    public Partidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        unirse = new javax.swing.JButton();
        crearPartida1 = new javax.swing.JButton();
        apodo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        unirse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráfico/Btn_BuscarPartida.png"))); // NOI18N
        unirse.setBorder(null);
        unirse.setBorderPainted(false);
        unirse.setContentAreaFilled(false);
        unirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unirseActionPerformed(evt);
            }
        });
        jPanel1.add(unirse);
        unirse.setBounds(620, 390, 500, 120);

        crearPartida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráfico/Btn_CrearPartida.png"))); // NOI18N
        crearPartida1.setToolTipText("");
        crearPartida1.setBorder(null);
        crearPartida1.setBorderPainted(false);
        crearPartida1.setContentAreaFilled(false);
        crearPartida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPartida1ActionPerformed(evt);
            }
        });
        jPanel1.add(crearPartida1);
        crearPartida1.setBounds(170, 400, 430, 106);

        apodo.setBackground(new java.awt.Color(207, 198, 229));
        apodo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        apodo.setForeground(new java.awt.Color(1, 18, 106));
        apodo.setBorder(null);
        jPanel1.add(apodo);
        apodo.setBounds(590, 280, 350, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráfico/PARTIDA.gif"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearPartida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPartida1ActionPerformed
        String name = apodo.getText().trim();
        if (name.isEmpty()) {
            return;
        }
        Servidor servidor = new Servidor(name);
        servidor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_crearPartida1ActionPerformed

    private void unirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unirseActionPerformed
        String name = apodo.getText().trim();
        if (name.isEmpty()) {
            return;
        }
        Cliente cliente = new Cliente(name);
        cliente.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_unirseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Partidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Partidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Partidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Partidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Partidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apodo;
    private javax.swing.JButton crearPartida1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton unirse;
    // End of variables declaration//GEN-END:variables
}
