/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import client.DrawingPanel;
import client.GuessPanel;
import client.StatusPanel;
import client.ToolsPanel;
import common.Protocol;
import java.awt.BorderLayout;
import java.awt.Font;
import java.io.PrintWriter;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author fvarelo
 */
public class ServidorGame extends javax.swing.JFrame {

    /**
     * Creates new form ClienteGame
     */
    private final String playerName;
    private final ToolsPanel tools;
    private final DrawingPanel drawing;
    private final GuessPanel guess;
    private final StatusPanel status;
    private final PrintWriter out;

    public ServidorGame(String playerName, java.io.PrintWriter out) {
        super("Draw It - " + playerName);
        this.playerName = playerName;
        this.out = out;
        initComponents();
        // Right after creating 'out' and before you ever press "Iniciar partida":
        this.out.println(Protocol.encode(Map.of("type", "JOIN", "player", playerName)));
        this.out.flush(); // extra safety if autoFlush wasn't used

        // Ocultar todos excepto el fondo
        Tiempo.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        jButton13.setVisible(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jScrollPane1.setVisible(true);
        jTextArea1.setVisible(true);
        jTextField1.setVisible(true);
        grosor.setVisible(true);
        lienzo.setVisible(true);
        lienzo1.setVisible(true);
        herramientas.setVisible(true);

// Mantener visible solo el fondo
        fondo.setVisible(true);

        setLayout(new BorderLayout());

        tools = new ToolsPanel(out, grosor, Tiempo);
        drawing = new DrawingPanel(out, tools);
        lienzo.removeAll(); // panel creado en el diseñador
        lienzo.setLayout(new BorderLayout());
        lienzo.add(drawing, BorderLayout.CENTER);
        lienzo.revalidate();
        lienzo.repaint();

        guess = new GuessPanel(out, playerName);
        status = new StatusPanel(tools);
        lienzo1.removeAll(); // panel creado en el diseñador
        lienzo1.setLayout(new BorderLayout());
        lienzo1.add(status, BorderLayout.CENTER);
        lienzo1.revalidate();
        lienzo1.repaint();

        setDefaultCloseOperation(EXIT_ON_CLOSE);

        // Estado inicial
        tools.setEnabled(false);
        drawing.setArtist(false);
        guess.setEnabled(false);
        this.out.println(Protocol.encode(Map.of("type", "START_REQUEST")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        Tiempo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lienzo = new visual.PanelRound();
        grosor = new slider_material.JsliderCustom();
        herramientas = new visual.PanelRound();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lienzo1 = new visual.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jButton13.setText("REINICIAR PARTIDA");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(630, 80, 150, 23);

        Tiempo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Tiempo.setForeground(new java.awt.Color(251, 178, 99));
        Tiempo.setText("jLabel2");
        jPanel1.add(Tiempo);
        Tiempo.setBounds(1140, 40, 200, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GROSOR");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(510, 80, 90, 30);

        lienzo.setBackground(new java.awt.Color(253, 248, 253));
        lienzo.setRadius(100);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel1.add(lienzo);
        lienzo.setBounds(50, 130, 1060, 570);

        grosor.setBackground(new java.awt.Color(103, 88, 230));
        grosor.setForeground(new java.awt.Color(103, 88, 230));
        grosor.setMaximum(30);
        grosor.setToolTipText("Grosor");
        grosor.setValue(15);
        jPanel1.add(grosor);
        grosor.setBounds(40, 80, 460, 30);

        herramientas.setLayout(null);

        jButton1.setText("jButton1");
        herramientas.add(jButton1);
        jButton1.setBounds(570, 10, 40, 23);

        jButton2.setText("jButton1");
        herramientas.add(jButton2);
        jButton2.setBounds(465, 10, 40, 23);

        jButton3.setText("jButton1");
        herramientas.add(jButton3);
        jButton3.setBounds(360, 10, 40, 23);

        jButton4.setText("jButton1");
        herramientas.add(jButton4);
        jButton4.setBounds(400, 10, 40, 23);

        jButton5.setText("jButton1");
        herramientas.add(jButton5);
        jButton5.setBounds(310, 10, 40, 23);

        jButton6.setText("jButton1");
        herramientas.add(jButton6);
        jButton6.setBounds(270, 10, 40, 23);

        jButton7.setText("jButton1");
        herramientas.add(jButton7);
        jButton7.setBounds(220, 10, 40, 23);

        jButton8.setText("jButton1");
        herramientas.add(jButton8);
        jButton8.setBounds(170, 10, 40, 23);

        jButton9.setText("jButton1");
        herramientas.add(jButton9);
        jButton9.setBounds(30, 10, 40, 23);

        jButton10.setText("jButton1");
        herramientas.add(jButton10);
        jButton10.setBounds(80, 10, 40, 23);

        jButton11.setText("jButton1");
        herramientas.add(jButton11);
        jButton11.setBounds(120, 10, 40, 23);

        jButton12.setText("jButton1");
        herramientas.add(jButton12);
        jButton12.setBounds(515, 10, 40, 23);

        jTextField1.setText("jTextField1");
        herramientas.add(jTextField1);
        jTextField1.setBounds(670, 10, 200, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráfico/Herramientas.png"))); // NOI18N
        herramientas.add(jLabel1);
        jLabel1.setBounds(0, 0, 1090, 50);

        jPanel1.add(herramientas);
        herramientas.setBounds(30, 20, 1070, 50);

        lienzo1.setBackground(new java.awt.Color(253, 248, 253));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lienzo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lienzo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(lienzo1);
        lienzo1.setBounds(1110, 190, 120, 500);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráfico/Lienzo.png"))); // NOI18N
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        out.println(Protocol.encode(Map.of("type", "START_REQUEST")));
    }//GEN-LAST:event_jButton13ActionPerformed
    public void handleMessage(String json) {
        Map<String, Object> msg = Protocol.decode(json);
        String type = (String) msg.get("type");
        if (type == null) {
            return;
        }

        switch (type) {
            case "START" -> {
                ImageIcon icon = new ImageIcon(getClass().getResource("/Gráfico/Lienzo.png"));

                // Mostrar todos los elementos de la interfaz
                Tiempo.setVisible(true);
                jButton1.setVisible(true);
                jButton2.setVisible(true);
                jButton3.setVisible(true);
                jButton4.setVisible(true);
                jButton5.setVisible(true);
                jButton6.setVisible(true);
                jButton7.setVisible(true);
                jButton8.setVisible(true);
                jButton9.setVisible(true);
                jButton10.setVisible(true);
                jButton11.setVisible(true);
                jButton12.setVisible(true);
                jButton13.setVisible(true);
                jLabel1.setVisible(true);
                jLabel2.setVisible(true);
                jScrollPane1.setVisible(true);
                jTextArea1.setVisible(true);
                jTextField1.setVisible(true);
                grosor.setVisible(true);
                lienzo.setVisible(true);
                lienzo1.setVisible(true);
                herramientas.setVisible(true);

                // Iniciar timer con duración enviada por el servidor
                int duration = ((Double) msg.get("duration")).intValue();
                tools.startTimer(duration);

                fondo.setIcon(icon);
                String artist = (String) msg.get("artist");
                boolean iAmArtist = playerName.equals(artist);

                // Cambiar pantalla de carga a la interfaz de juego
                setLayout(new BorderLayout());
                herramientas.removeAll();
                herramientas.setLayout(new BorderLayout());
                herramientas.add(tools, BorderLayout.CENTER);
                herramientas.revalidate();
                herramientas.repaint();

                lienzo.removeAll();
                lienzo.setLayout(new BorderLayout());
                lienzo.add(drawing, BorderLayout.CENTER);
                lienzo.revalidate();
                lienzo.repaint();

                // Configurar roles
                tools.setArtist(iAmArtist);   // muestra palabra o campo adivinanza
                tools.setEnabled(iAmArtist);  // habilita herramientas solo al dibujante
                drawing.setArtist(iAmArtist);
                guess.setEnabled(!iAmArtist);

                // Inicializar estado
                drawing.clearCanvasLocal();
                status.setArtist(artist);
                status.setRound(((Double) msg.get("round")).intValue());
                status.setDuration(duration);

                // Si el servidor envía la palabra en START, mostrarla al dibujante
                if (msg.containsKey("value")) {
                    tools.setSecretWord((String) msg.get("value"));
                }

                revalidate();
                repaint();
            }

            case "WORD" -> {
                // Mensaje separado para enviar palabra al dibujante
                tools.setSecretWord((String) msg.get("value"));
            }

            case "DRAW" ->
                drawing.addRemoteStroke(msg);

            case "CLEAR" ->
                drawing.clearCanvasRemote();

            case "TIME" -> {
                int remaining = ((Double) msg.get("remaining")).intValue();
                status.setRemaining(remaining);
                tools.setTime(remaining); // ✅ también actualiza ToolsPanel
            }

            case "WINNER" -> {
                String winner = (String) msg.get("player");
                String word = (String) msg.get("word");
                status.updateScores((java.util.List<Map<String, Object>>) msg.get("scores"));
                JOptionPane.showMessageDialog(this, "Ganador: " + winner + " | Palabra: " + word);
            }

            case "ROUND_END" -> {
                String result = (String) msg.get("result");
                if ("timeout".equals(result)) {
                    String word = (String) msg.get("word");
                    JOptionPane.showMessageDialog(this, "Tiempo agotado. La palabra era: " + word);
                }
                tools.setEnabled(false);
                drawing.setArtist(false);
                guess.setEnabled(false);
            }

            case "SCORES" ->
                status.updateScores((java.util.List<Map<String, Object>>) msg.get("players"));

            default -> {
                // opcional: log de mensajes desconocidos
                System.out.println("Mensaje desconocido: " + msg);
            }
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tiempo;
    private javax.swing.JLabel fondo;
    private slider_material.JsliderCustom grosor;
    private visual.PanelRound herramientas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private visual.PanelRound lienzo;
    private visual.PanelRound lienzo1;
    // End of variables declaration//GEN-END:variables

}
